version: "3.9"
services:
  dev:
    container_name: "rust-dev"
    image: rust:1.75
    volumes:
      - .:/app
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    command: ["sh", "-c", "cd /app && cargo run -- --bind 0.0.0.0:8000"]
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '0.4GB'



  postgres:
    container_name: postgres-rust
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./watch_init_sql.sh:/docker-entrypoint-initdb.d/watch_init_sql.sh
      - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '0.4GB'
